[package]
name = "github_adapter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.28"
octocrab = "0.25.1"
serde_json = "1.0.99"
trustfall = "0.5.1"
